fix(test): flaky test case in KMETADTA command (#3150)
The root cause is generating random strings in a short time
and using them to create fields for Hash/Set/ZSet.

To fix this issue, just avoid using random strings if unnecessary
which will also make the code more concise.


```
--- FAIL: TestKMetadata (1.04s)
    --- FAIL: TestKMetadata/Test_KMetadata_for_set_type (0.00s)
        kmetadata_test.go:170: 
            	Error Trace:	/__w/kvrocks/kvrocks/tests/gocase/unit/kmetadata/kmetadata_test.go:170
            	Error:      	Not equal: 
            	            	expected: 4
            	            	actual  : 3
            	Test:       	TestKMetadata/Test_KMetadata_for_set_type
FAIL
```